controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Ciclista;
use yii\data\SqlDataProvider;
use yii\data\ActiveDataProvider;
use app\models\Puerto;
use app\models\Etapa;


class SiteController extends Controller
{
    public function actionActiverecord1(){
       $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("COUNT(*) as Ciclistas"),
            'pagination'=>[
                    'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Ciclistas'],
            "titulo"=>"Consulta 1 con Active Record",
            "enunciado"=>"Número de ciclistas que hay",
            "sql"=>"SELECT COUNT(*) FROM ciclista;", 
        ]);
    } 
    public function actionDao1(){
        $numero = Yii::$app->db
                    ->createCommand("select COUNT(*) as Ciclistas FROM ciclista")
                    ->queryScalar();                              
        $dataProvider = new SqlDataProvider([
            'sql' =>"select COUNT(*) as Ciclistas FROM ciclista",
            'totalCount'=>$numero,
            'pagination'=>[
            'pageSize'=>0,
                ]
            ]);       
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
                "campos"=>['Ciclistas'],
            "titulo"=>"Consulta 1 con DAO",
            "enunciado"=>"Número de ciclistas que hay",
            "sql"=>"SELECT COUNT(*) AS ciclistas FROM ciclista;",
            
        ]);
    } 
    public function actionActiverecord2(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("COUNT(*) as Ciclistas_Banesto") ->where("nomequipo='Banesto'"),
            'pagination'=>[
                    'pageSize'=>0,
                ]
            ]);       
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Ciclistas_Banesto'],
            "titulo"=>"Consulta 2 con Active Record",
            "enunciado"=>"Número de ciclistas que hay del equipo Banesto",
            "sql"=>"SELECT COUNT(*) AS Número_Ciclistas_Equipo_Banesto FROM ciclista WHERE nomequipo='Banesto';
;",          
        ]);
    } 
    public function actionDao2(){
      $numero = Yii::$app->db
                    ->createCommand("SELECT COUNT(*) as Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto'")
                    ->queryScalar();
        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT COUNT(*) as Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto'",
            'totalCount'=>$numero,
            'pagination'=>[
            'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Ciclistas_Banesto'],
            "titulo"=>"Consulta 2 con DAO",
            "enunciado"=>"Número de ciclistas que hay del equipo Banesto",
            "sql"=>"SELECT COUNT(*) AS Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto';",   
        ]);
    }  
    public function actionActiverecord3(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("AVG(edad) as Edad_Media"),
            'pagination'=>[
                    'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media'],
            "titulo"=>"Consulta 3 con Active Record",
            "enunciado"=>"Edad media de los ciclistas.",
            "sql"=>"SELECT AVG(edad) AS Edad_Media FROM ciclista;",
        ]);
} 
    public function actionDao3(){
          $numero = Yii::$app->db
                    ->createCommand("SELECT AVG(edad) as Edad_Media FROM ciclista")
                    ->queryScalar();
        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT AVG(edad) as Edad_Media FROM ciclista",
            'totalCount'=>$numero,
            'pagination'=>[
            'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media'],
            "titulo"=>"Consulta 3 con DAO",
            "enunciado"=>"Edad media de los ciclistas.",
            "sql"=>"SELECT AVG(edad) AS Edad_Media FROM ciclista;",
        ]);
    }  
    public function actionActiverecord4(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("AVG(edad) as Edad_Media_Ciclistas_Banesto") ->where("nomequipo='Banesto'"),
            'pagination'=>[
                    'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media_Ciclistas_Banesto'],
            "titulo"=>"Consulta 4 con Active Record",
            "enunciado"=>"La edad media de los ciclistas del equipo Banesto",
            "sql"=>"SELECT AVG(edad) AS Edad_Media_Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto';",
        ]);
} 
    public function actionDao4(){
          $numero = Yii::$app->db
                    ->createCommand("SELECT AVG(edad) Edad_Media_Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto'")
                    ->queryScalar();
        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT AVG(edad) Edad_Media_Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto'",
            'totalCount'=>$numero,
            'pagination'=>[
            'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media_Ciclistas_Banesto'],
            "titulo"=>"Consulta 4 con DAO",
            "enunciado"=>"La edad media de los ciclistas del equipo Banesto",
            "sql"=>"SELECT AVG(edad) AS Edad_Media_Ciclistas_Banesto FROM ciclista WHERE nomequipo='Banesto';",
        ]);
    }  
    public function actionActiverecord5(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("AVG(edad) as Edad_Media_Por_Equipo, nomequipo") ->groupBy("nomequipo"),
            'pagination'=>[
                    'pageSize'=>5,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media_Por_Equipo','nomequipo'],
            "titulo"=>"Consulta 5 con Active Record",
            "enunciado"=>"La edad media de los ciclistas por cada equipo",
            "sql"=>"SELECT AVG(edad) AS Edad_Media_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo;" , 
        ]);
} 
    public function actionDao5(){
          $numero = Yii::$app->db
                    ->createCommand("SELECT AVG(edad) as Edad_Media_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo")
                    ->queryScalar();         
        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT AVG(edad) as Edad_Media_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo",
            'pagination'=>[
            'pageSize'=>5,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Edad_Media_Por_Equipo','nomequipo'],
            "titulo"=>"Consulta 5 con DAO",
            "enunciado"=>"La edad media de los ciclistas por cada equipo",
            "sql"=>"SELECT AVG(edad) AS Edad_Media_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo;",
        ]);
    } 
    public function actionActiverecord6(){
        $dataProvider = new ActiveDataProvider([
            'query' => Ciclista::find() ->select("COUNT(nombre) as Numero_Ciclistas_Por_Equipo, nomequipo") ->groupBy("nomequipo"),
            'pagination'=>[
                    'pageSize'=>5,
                ]
            ]);
        
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Numero_Ciclistas_Por_Equipo', 'nomequipo'],
            "titulo"=>"Consulta 6 con Active Record",
            "enunciado"=>"El número de ciclistas por equipo",
            "sql"=>"SELECT COUNT(nombre) as Numero_Ciclistas_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo;", 
      
            
        ]);
 
    } 
    public function actionDao6(){
          $numero = Yii::$app->db
                    ->createCommand("SELECT COUNT(nombre) as Numero_Ciclistas_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo")
                    ->queryScalar();
        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT COUNT(nombre) as Numero_Ciclistas_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo",
            'pagination'=>[
            'pageSize'=>0,
                ]
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Numero_Ciclistas_Por_Equipo','nomequipo'],
            "titulo"=>"Consulta 6 con DAO",
            "enunciado"=>"El número de ciclistas por equipo",
            "sql"=>"SELECT COUNT(nombre) as Numero_Ciclistas_Por_Equipo, nomequipo FROM ciclista GROUP BY nomequipo;",      
        ]);
    }
    public function actionActiverecord7(){
        $dataProvider = new ActiveDataProvider([
            'query' => Puerto::find() ->select("COUNT(*) as Número_Total_Puertos")
            ]);
        return $this->render("resultado",[
            "resultados"=>$dataProvider,
            "campos"=>['Número_Total_Puertos'],
            "titulo"=>"Consulta 7 con Active Record",
            "enunciado"=>"El número total de puertos",
            "sql"=>"SELECT COUNT(*) AS Número_Total_Puertos FROM puerto;",        

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">   
    <h1>Ejercicio 2 consultas</h1> 
    <p>Ejercicios del 1 al 12</p> 
    </div>

    
    <div class="body-content">

        <div class="row">
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 1</h2>
                <p>Número de ciclistas que hay</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord1'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao1'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 2</h2>
                <p>Número de ciclistas que hay del equipo Banesto</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord2'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao2'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 3</h2>
                <p>Edad media de los ciclistas</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord3'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao3'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 4</h2>
                <p>La edad media de los del equipo Banesto</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord4'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao4'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 5</h2>
                <p>La edad media de los ciclistas por cada equipo</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord5'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao5'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 6</h2>
                <p>El número de ciclistas por equipo</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord6'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao6'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 7</h2>
                <p>El número total de puertos</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord7'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao7'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 8</h2>
                <p>El número total de puertos mayores de 1500</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord8'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao8'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 9</h2>
                <p>Listar el nombre de los equipos que tengan más de 4 ciclistas</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord9'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao9'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 10</h2>
                <p>Listar el nombre de los equipos que tengan más de 4 ciclistas cuya edad esté entre 28 y 32</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord10'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao10'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 11</h2>
                <p>Indícame el número de etapas que ha ganado cada uno de los ciclistas</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord11'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao11'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                <h2>Ejercicio 12</h2>
                <p>Indícame el dorsal de los ciclistas que hayan ganado más de una etapa</p>
                <p>
                    <?= Html::a('Active Record', ['site/activerecord12'], ['class' => 'btn btn-primary'])?>
                    <?= Html::a('DAO', ['site/dao12'], ['class' => 'btn btn-default'])?>
                </p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/resultado.php
<?php
use yii\grid\GridView;
?>

<div class="jumbotron">
    <h2><?=$titulo?></h2>
    <p class="lead"><?= $enunciado ?></p>
    <div class="well">
        <?= $sql ?>
    </div>
</div>

  <?=GridView::widget([
            'dataProvider' => $resultados,
            'columns'=>$campos,
    ]); ?>